name: ferry_ticket_app
description: A Flutter application for online ferry ticket purchases.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.3.0
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_database: ^10.2.3
  firebase_app_check: ^0.2.1+8
  cloud_firestore: ^4.8.1
  shared_preferences: ^2.2.2
  intl: 0.19.0
  image_picker: ^1.0.7
  firebase_storage: ^11.2.3
  google_fonts: ^6.2.1
  flutter_image_compress: ^2.1.0
  qr_flutter: ^4.1.0
  permission_handler: ^11.0.1
  geolocator: ^10.0.1
  flutter_launcher_icons: ^0.14.3
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/fery.png"
  min_sdk_android: 21
  
flutter:
  uses-material-design: true
  assets:
    - assets/boat.png
    - assets/waves.png
    - assets/ferygogo.png
    - assets/fery.png
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

