name: ferry_ticket_app
description: A Flutter application for online ferry ticket purchases.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.3.0
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_database: ^11.3.5
  firebase_app_check: ^0.3.2+5
  cloud_firestore: ^5.6.7
  shared_preferences: ^2.2.2
  intl: 0.19.0
  image_picker: ^1.0.7
  firebase_storage: ^12.4.5
  google_fonts: ^6.2.1
  flutter_image_compress: ^2.1.0
  qr_flutter: ^4.1.0
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.0
  flutter_launcher_icons: ^0.14.3
  weather_icons: ^3.0.0
  image_cropper: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/fery.png"
  min_sdk_android: 21
  
flutter:  
  uses-material-design: true
  assets:
    - assets/boat.png
    - assets/waves.png
    - assets/ferygogo.png
    - assets/icon/fery.png
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

