// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4dX-5g965l-PveLYEt3QfmZj48_NthJo',
    appId: '1:290091360925:web:d2bc05ad79101029c9aa74',
    messagingSenderId: '290091360925',
    projectId: 'ferygogo-eb2cb',
    authDomain: 'ferygogo-eb2cb.firebaseapp.com',
    storageBucket: 'ferygogo-eb2cb.firebasestorage.app',
    measurementId: 'G-5V5KCJRPB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQU5lHH_zzpFans6vpEOuiOYkDFsxOCqk',
    appId: '1:290091360925:android:7066a2b406810a17c9aa74',
    messagingSenderId: '290091360925',
    projectId: 'ferygogo-eb2cb',
    storageBucket: 'ferygogo-eb2cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNFE2YEnc1OhXgWyzMy0K7JG6KbZDvbUY',
    appId: '1:290091360925:ios:5f6b4de80006a813c9aa74',
    messagingSenderId: '290091360925',
    projectId: 'ferygogo-eb2cb',
    storageBucket: 'ferygogo-eb2cb.firebasestorage.app',
    iosBundleId: 'com.example.ferygogo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNFE2YEnc1OhXgWyzMy0K7JG6KbZDvbUY',
    appId: '1:290091360925:ios:5f6b4de80006a813c9aa74',
    messagingSenderId: '290091360925',
    projectId: 'ferygogo-eb2cb',
    storageBucket: 'ferygogo-eb2cb.firebasestorage.app',
    iosBundleId: 'com.example.ferygogo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4dX-5g965l-PveLYEt3QfmZj48_NthJo',
    appId: '1:290091360925:web:697c9562510ab214c9aa74',
    messagingSenderId: '290091360925',
    projectId: 'ferygogo-eb2cb',
    authDomain: 'ferygogo-eb2cb.firebaseapp.com',
    storageBucket: 'ferygogo-eb2cb.firebasestorage.app',
    measurementId: 'G-1R93SHNX5K',
  );

}